aparelhos/urls.py
from django.urls import path
from aparelhos import views

app_name = 'aparelhos'

urlpatterns = [
    path('consumo/<slug:slug>/', views.simulator, name='teste'),
    path('', views.lista_Aparelho, name='lista_aparelhos'),
    path('cadastrar-aparelho/', views.cadastro_Aparelho, name='save_aparelho'),
    path('alterar/<int:pk>/', views.edit_aparelho, name='edit_aparelho'),
    path('apagar/<int:pk>/', views.deletar_aparelho, name='deletar_aparelho'),
    path('insercao-aparelho-ambiente/', views.relation, name='relation'),
    
]

consumo_de_energia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('simulador/', include('ambientes.urls', namespace='ambientes')),
    path('simulador/aparelhos/', include('aparelhos.urls', namespace='aparelhos')),
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.pagInicio, name='home' ),
    
]

aparelhos/models.py
from django.db import models
from ambientes.models import Ambiente
from django.db.models import signals
from django.urls import reverse
from consumo_de_energia.utils import slug_pre_save

# Create your models here.

class AparelhoManager(models.Manager):
    
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(potencia__icontains=query))

class Aparelho(models.Model):
    name = models.CharField(verbose_name='Nome do aparelho', max_length=100)
    slug = models.SlugField(verbose_name='Atalho', blank=True, max_length=100, unique=True)
    potencia = models.IntegerField(verbose_name='Potencia em watts', null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='Criado em', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Atualizado em', auto_now=True)

    objects = AparelhoManager()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'aparelho'
        verbose_name = 'aparelho'
        verbose_name_plural = 'Aparelhos'
        ordering = ['name']


class Aparelho_Ambiente(models.Model):
    
    STATUS_CHOICES = (
        (1, 'minutos/dia'),
        (2, 'horas/dia'),
    )
    
    ambiente = models.ForeignKey(Ambiente, verbose_name='Ambiente', related_name='ambientes', on_delete=models.deletion.DO_NOTHING)
    aparelho = models.ForeignKey(Aparelho, verbose_name='Aparelho', related_name='aparelhos', on_delete=models.deletion.DO_NOTHING)
    quantidade = models.IntegerField('Quantidade', default=0, blank=True,)
    tempo = models.IntegerField(verbose_name='Tempo de uso', null=True, blank=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=2, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    
    class Meta:
        db_table = 'aparelho_ambiente'
        verbose_name = 'Aparelho e Ambiente'
        verbose_name_plural = 'Aparelhos e Ambientes'
        unique_together = (('aparelho', 'ambiente'))

#Signals

signals.pre_save.connect(slug_pre_save, sender=Aparelho)

aparelhos/forms.py
from django import forms
from aparelhos.models import Aparelho, Aparelho_Ambiente

#criação do formulario de preenchimento do aparelho.

class AparelhoForm(forms.ModelForm):

    class Meta:
        model = Aparelho
        fields = ['name', 'potencia']



class RelationForm(forms.ModelForm):

    class Meta:
        model = Aparelho_Ambiente
        fields = ['ambiente', 'aparelho', 'quantidade', 'tempo', 'status']

    

aparelhos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AparelhoForm, RelationForm
from django.contrib import messages
from .models import Aparelho, Aparelho_Ambiente
from ambientes.models import Ambiente

# Create your views here.

def calcSimulador(request):
    pass

#função que cadastra o aparalho
def cadastro_Aparelho(request):
    template_name = 'aparelhos/cadastro_aparelho.html'
    context = {}
    if request.method == 'POST':
        form = AparelhoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Aparelho cadastrado com sucesso.')
            return redirect('aparelhos:lista_aparelhos')
    else:
        form = AparelhoForm()
    context['form'] = form
    return render(request, template_name, context)

#função que mostra uma lista de aparelhos
def lista_Aparelho(request):
    aparelhos = Aparelho.objects.all()
    context = {
        'aparelhos':aparelhos,
    }
    template_name = 'aparelhos/index.html'
    return render(request, template_name, context)

def edit_aparelho(request, pk):
    aparelho = get_object_or_404(Aparelho, pk=pk)
    
    if request.method == 'POST':
        form = AparelhoForm(request.POST, instance=aparelho)
        if form.is_valid():
            form.save()
            messages.success(request, 'Os dados foram alterados com sucesso')
            return redirect('aparelhos:index')
    else:
        form = AparelhoForm(instance=aparelho)
    template_name = 'aparelhos/editar_aparelho.html'
    context = {
        'form':form,
    }
    return render(request, template_name, context)

def deletar_aparelho(request, pk):
    aparelho = get_object_or_404(Aparelho, pk=pk)
    aparelho.delete()
    messages.success(request, 'Aparelho apagado com sucesso!')
    return redirect('aparelho:lista_aparelhos')


def relation(request):
    template_name = 'aparelhos/relations.html'
    context = {}
    if request.method == 'POST':
        form = RelationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Aparelho adicionado ao ambiente com sucesso.')
            return redirect('aparelhos:lista_aparelhos')
    else:
        form = RelationForm()
    context['form'] = form
    return render(request, template_name, context)

def simulator(request, slug):
    context={}
    ambientes = Ambiente.objects.prefetch_related('ambientes').order_by('id')
    apps = Aparelho_Ambiente.objects.prefetch_related('ambientes','aparelhos').values(
        'aparelho__name'
    ).filter(ambiente__slug=slug)
    context = {

        'ambientes':ambientes,
        'apps':apps,
    }
    return render(request, 'aparelhos/simulador.html', context)

aparelhos/templates/aparelhos/cadastro_aparelho.html
{% extends "base.html" %}

{% block content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form.non_field_errors }}

        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}

        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
        </div>
    </fieldset>
</form>   
{% endblock %}

aparelhos/templates/aparelhos/editar_aparelho.html
% extends "base.html" %}

{% block title %}Atualizar Aparelho{% endblock %}

{% block content %}
<section class="default light">
    <div class="section-title">Aparelho</div>
    <div class="section-desc"></div>
    <div class="section-body">
        <div class="section-aboutus">
            <div class="section-aboutus--left">
                <form class="pure-form pure-form-aligned" method="post">
                    {% csrf_token %}
                    <fieldset>
                        {{ form.non_field_errors }}
                
                        {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                
                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Alterar</button>
                        </div>
                    </fieldset>
                </form>   
            </div>
        </div>
    </div>
</section>
{% endblock %}

aparelhos/templates/aparelhos/index.html
{% extends "base.html" %}

{% load static %}
<h1>BEM VINDO A PAGINA CADASTRO</h1>
{% block content %}
<section class="default light">
    <div class="section-title">Inserir </div>
    <div class="section-desc"></div>
    <div class="section-body">
        <div class="section-aboutus">
            <div class="section-aboutus--left">
                <h4>Aparelho</h4>
                <a class="button" style="display: inline-block; margin-bottom:5px;" 
                    href="{% url 'aparelhos:save_aparelho' %}">Cadastrar um Aparelho</a>
    
                                         
            </div>
            <div class="section-aboutus--right">
                {% block aparelho_content %}
                    
                    <table class="pure-table">
                        <thead>
                            <tr>
                                <th>
                                    Nome
                                </th>
                                <th>
                                    Data de criação
                                </th>
                                <th>
                                    Ação
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for aparelho in aparelhos %}
                            <tr class="{% cycle '' 'pure-table-odd' %}">
                                <td>
                                    {{ aparelho|upper }}
                                </td>
                                <td>
                                    {{ aparelho.created_at }}
                                </td>
                                <td>
                                    <div class="pure-button-group" role="group" aria-label="...">
                                        <a href="{% url 'aparelhos:edit_aparelho' aparelho.pk %}" class="pure-button">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="{% url 'aparelhos:deletar_aparelho' aparelho.pk %}" class="pure-button">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan=3>Não existes ambientes a ser listados</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endblock aparelho_content %}
            </div>
        </div>
    </div>
</section>                  
        
{% endblock content %}

aparelhos/templates/aparelhos/lista_aparelho.html
{% extends "ambientes/lista_ambientes.html" %}

{% block aparelho_content %}

<table>
    <tr>
      <th>Nome do Aparelho</th>
      <th>Potência</th>
      <th>Tempo</th>
      <th>Data de Criação</th>
    </tr>
    {% for aparelho in aparelhos %}
    <tr>
      <td>{{ aparelho.name }}</td>
      <td>{{ aparelho.potencia }}</td>
      <td>{{ aparelho.tempo }}</td>
      <td>{{ aparelho.created_at }}</td>
    </tr>
    {% empty %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <p>Não existe aparelho cadastrado.</p>
            </div>
        </div>
    </div>
    {% endfor %}
</table>
{% endblock%}

aparelhos/templates/aparelhos/relations.html
{% extends "base.html" %}

{% block title %}Cadastro aparelho ao ambiente{% endblock %}

{% block content %}
<section class="default light">
    <div class="section-title">Ambiente</div>
    <div class="section-desc"></div>
    <div class="section-body">
        <div class="section-aboutus">
            <div class="section-aboutus--left">
                <form class="pure-form pure-form-stacked" method="post">
                    {% csrf_token %}
                    <fieldset>
                        {{ form.non_field_errors }}

                        {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}

                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                        </div>
                    </fieldset>
                </form> 
                </div>
        </div>
    </div>
</section>  
{% endblock %}

aparelhos/templates/aparelhos/simulador.html
{% extends "base.html" %}

{% block content %}
<div class="body">
    {% for ambiente in ambientes %}
        <button class="tablink" onclick="openPage('{{ ambiente.name }}', this, 'red')"><a>{{ ambiente.name }}</a></button>
    
        <div id="{{ ambiente.name }}" class="tabcontent">
            {% for app in apps %}
                {{ app }}
            {% empty %}
                <p>Nenhum aparelho encontrado</p>
            {% endfor %}
        </div>
    {% endfor %}
    <script>
    function openPage(pageName, elmnt, color) {
        // Hide all elements with class="tabcontent" by default */
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        // Remove the background color of all tablinks/buttons
        tablinks = document.getElementsByClassName("tablink");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].style.backgroundColor = "";
        }

        // Show the specific tab content
        document.getElementById(pageName).style.display = "block";

        // Add the specific color to the button used to open the tab content
        elmnt.style.backgroundColor = color;
    }

    // Get the element with id="defaultOpen" and click on it
    document.getElementById("defaultOpen").click();
</script>
</body>
{% endblock %}