ambientes/urls.py
from django.urls import path
from ambientes import views

app_name = 'ambientes'

urlpatterns = [
    path('', views.index, name='index'),
    path('ambientes/cadastrar/', views.Cadastrar_ambiente, name='save_ambiente'),
    path('ambientes/apagar/<int:pk>/', views.deletar_ambiente, name='del_ambiente'),
    path('ambientes/alterar/<int:pk>/', views.editar_ambiente, name='edit_ambiente'),
    path('ambientes/<slug:slug>/', views.select_ambiente, name='select_ambiente'),
]

consumo_de_energia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('simulador/', include('ambientes.urls', namespace='ambientes')),
    path('simulador/aparelhos/', include('aparelhos.urls', namespace='aparelhos')),
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.pagInicio, name='home' ),
    
]

ambientes/models.py
from django.db import models
from django.db.models import signals
from django.urls import reverse
from consumo_de_energia.utils import slug_pre_save

# Create your models here.

class Ambiente(models.Model):

    name = models.CharField(verbose_name='Nome do ambiente', max_length=100, blank=True)
    slug = models.SlugField(verbose_name='Atalho', blank=True, unique=True, max_length=100)
    created_at = models.DateTimeField(verbose_name='Criado em',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Atualizado em', auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ambientes:select_ambiente', kwargs={'slug':self.slug})
    
    class Meta:
        db_table = 'ambiente'
        verbose_name = 'Ambiente'
        verbose_name_plural = 'Ambientes'
        ordering = ['name']

#signals

signals.pre_save.connect(slug_pre_save, sender=Ambiente)

ambientes/forms.py
from django import forms
from .models import Ambiente



class AmbienteForm(forms.ModelForm):

    class Meta:
        model = Ambiente
        fields = ['name']

ambientes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from ambientes.models import Ambiente
from aparelhos.forms import AparelhoForm
from .forms import AmbienteForm
from django.contrib import messages

# Create your views here.


def index(request):
    ambientes = Ambiente.objects.all()
    template_name = 'ambientes/index.html'
    context = {
        'ambientes':ambientes,
    }
    return render(request, template_name, context)

def Cadastrar_ambiente(request):
    template_name = 'ambientes/cadastro_ambiente.html'
    ambientes = Ambiente.objects.all()
    context = {}
    if request.method == 'POST':
        form = AmbienteForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success = (request, 'Ambiente cadastrado com sucesso!')
            return redirect('ambientes:index')
    else:
        form = AmbienteForm()
    context = {
        'form':form,
        'ambientes':ambientes
    }
    return render(request, template_name, context)

def editar_ambiente(request, pk):
    ambientes = get_object_or_404(Ambiente, pk=pk)

    if request.method == 'POST':
        form = AmbienteForm(request.POST, instance=ambientes)
        if form.is_valid():
            form.save()
            messages.success = (request, 'Ambiente alterado com sucesso!')
            return redirect('ambientes:index')
    else:
        form = AmbienteForm(instance=ambientes)
    template_name = 'ambientes/update_ambiente.html'
    context = {
        'form':form,
    }
    return render(request, template_name, context)



def deletar_ambiente(request, pk):
    ambientes = get_object_or_404(Ambiente, pk=pk)
    ambientes.delete()
    messages.success(request, 'Aparelho apagado com sucesso!')
    return redirect('ambientes:index')


def select_ambiente(request, slug):
    ambiente = get_object_or_404(Ambiente, slug=slug)
    context = {}
    template_name = 'aparelhos/lista_aparelho.html'
    if request.method == 'POST':
        form = AparelhoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Aparelho cadastrado com sucesso!')
            return redirect('aparelhos:lista-aparelhos')
    else:
        form = AparelhoForm()
    context['form'] = form
    context['ambiente'] = ambiente
    return render(request, template_name, context)

ambientes/templates/ambientes/cadastro_ambiente.html
{% extends "base.html" %}

{% block title %}Cadastrar Ambiente{% endblock %}

{% block content %}
<section class="default light">
    <div class="section-title">Ambiente</div>
    <div class="section-desc"></div>
    <div class="section-body">
        <div class="section-aboutus">
            <div class="section-aboutus--left">
                <form class="pure-form pure-form-aligned" method="post">
                    {% csrf_token %}
                    <fieldset>
                        {{ form.non_field_errors }}
                
                        {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                
                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                        </div>
                    </fieldset>
                </form>   
            </div>
        </div>
    </div>
</section>
{% endblock %}

ambientes/templates/ambientes/index.html
{% extends "base.html" %}

{% load static %}
<h1>BEM VINDO A PAGINA CADASTRO</h1>
{% block content %}
<section class="default light">
    <div class="section-title">Inserir </div>
    <div class="section-desc"></div>
    <div class="section-body">
        <div class="section-aboutus">
            <div class="section-aboutus--left">
                <h4>Ambientes</h4>
                <a class="button" style="display: inline-block; margin-bottom:5px;" 
                    href="{% url 'ambientes:save_ambiente' %}">Cadastrar um Ambiente</a>
    
                                         
            </div>
            <div class="section-aboutus--right">
                {% block ambiente_content %}
                    
                    <table class="pure-table">
                        <thead>
                            <tr>
                                <th>
                                    Nome
                                </th>
                                <th>
                                    Data de criação
                                </th>
                                <th>
                                    Ação
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ambiente in ambientes %}
                            <tr class="{% cycle '' 'pure-table-odd' %}">
                                <td>
                                    {{ ambiente|upper }}
                                </td>
                                <td>
                                    {{ ambiente.created_at }}
                                </td>
                                <td>
                                    <div class="pure-button-group" role="group" aria-label="...">
                                        <a href="{% url 'ambientes:edit_ambiente' ambiente.pk %}" class="pure-button">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="{% url 'ambientes:del_ambiente' ambiente.pk %}" class="pure-button">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan=3>Não existes ambientes a ser listados</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endblock ambiente_content %}
            </div>
        </div>
    </div>
</section>                  
        
{% endblock content %}

ambientes/templates/ambientes/lista_ambientes.html
{% extends "ambientes/index.html" %}

{% load static %}

{% block ambiente_content %}

<!--<h4>Ambientes</h4>
        <table class="pure-table">
            <thead>
                <tr>
                    <th>
                        Nome
                    </th>
                    <th>
                        Data de criação
                    </th>
                    <th>
                        Ação
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for ambiente in ambientes %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                        {{ ambiente }}
                    </td>
                    <td>
                        {{ ambiente.created_at }}
                    </td>
                    <td>
                        <div class="pure-button-group" role="group" aria-label="...">
                            <a href="" class="pure-button"><i class="fas fa-edit"></i></a>
                            <a href="" class="pure-button"><i class="fas fa-trash-alt"></i></a>
                        </div>
                    </td>
                </tr>
                {% empty %}
                <p>Não existe dados</p>
                {% endfor %}
            </tbody>
        </table>-->
{% endblock %}

ambientes/templates/ambientes/update_ambiente.html
{% extends "base.html" %}

{% block title %}Atualizar Ambiente{% endblock %}

{% block content %}
<section class="default light">
    <div class="section-title">Ambiente</div>
    <div class="section-desc"></div>
    <div class="section-body">
        <div class="section-aboutus">
            <div class="section-aboutus--left">
                <form class="pure-form pure-form-aligned" method="post">
                    {% csrf_token %}
                    <fieldset>
                        {{ form.non_field_errors }}
                
                        {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                
                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Alterar</button>
                        </div>
                    </fieldset>
                </form>   
            </div>
        </div>
    </div>
</section>
{% endblock %}