ambientes/urls.py
from django.urls import path
from ambientes import views

app_name = 'ambientes'

urlpatterns = [
    path('', views.index, name='index'),
    path('ambientes/cadastrar/', views.Cadastrar_ambiente, name='save_ambiente'),
    path('ambientes/apagar/<int:pk>/', views.deletar_ambiente, name='del_ambiente'),
    path('ambientes/alterar/<int:pk>/', views.editar_ambiente, name='edit_ambiente'),
    path('ambientes/<slug:slug>/', views.select_ambiente, name='select_ambiente'),
]

aparelhos/urls.py
from django.urls import path
from aparelhos import views

app_name = 'aparelhos'

urlpatterns = [
    path('consumo/<slug:slug>/', views.simulator, name='teste'),
    path('', views.lista_Aparelho, name='lista_aparelhos'),
    path('cadastrar-aparelho/', views.cadastro_Aparelho, name='save_aparelho'),
    path('alterar/<int:pk>/', views.edit_aparelho, name='edit_aparelho'),
    path('apagar/<int:pk>/', views.deletar_aparelho, name='deletar_aparelho'),
    path('insercao-aparelho-ambiente/', views.relation, name='relation'),
    
]

consumo_de_energia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('simulador/', include('ambientes.urls', namespace='ambientes')),
    path('simulador/aparelhos/', include('aparelhos.urls', namespace='aparelhos')),
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.pagInicio, name='home' ),
    
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/pure-min.css" integrity="sha384-cg6SkqEOCV1NbJoCu11+bm0NvBRc8IYLRGXkmNrqUBfTjmMYwNKPWBTIKyw9mHNJ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    
    
    <title>{% block title %}Consumo de Energia{% endblock %}</title>
</head>
<body>
    {% block menu %}
        <input type="checkbox" id="check"/>
        <label id="icone" for="check"><img src="{% static 'img/botao-iconN.png' %}"/></label>
        <div class="barra">
            <nav>
                {% for ambiente in ambientes %}
                <a href=""><div class="link">{{ ambiente.name }}</div></a>
                {% empty %}
                <a href=""><div class="link">Inicie para carregar os ambientes</div></a>
                {% endfor %}
            </nav>
        </div>
    {% endblock menu %}
    <header class=header-menu>
        <div class="header">
            <div class="logo">
                <a href="{% url 'core:home' %}">
                    <img src="{% static 'img/new_logo.png' %}"/>
                </a>
            </div>
            <div class="menu">
                <nav>
                    <ul>
                        <li><a href="">sala</a></li>
                        <li><a href="">cozinha</a></li>
                        <li><a href="">quarto</a></li>
                        <li><a href="">banheiro</a></li>
                        <li><a href="">garagem</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    {% if messages %}
    <div id ="fadeOut" class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>  
    {% endif %}
    {% block content %}{% endblock %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>
    <script type="text/javascript">
            setTimeout(function() {
                $('#fadOut').fadeOut('fast');
            }, 3000);
        </script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <footer>
        <div class="footer_copia">
                Copyright - Todos os direitos reservados 
        </div>   
    </footer>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <main>
        <section class="banner">
            <button class="btn-prev" type="button">Preview</button>
            <div class="sliders">
                <div class="slide">
                    <div class="slidearea">
                        <h1>Simulador de Consumo<br/><span>Projeto para fins academêmicos</span></h1>
                        
                        <a href="{% url 'aparelhos:teste' slug='sala' %}">Iniciar Simulação</a>
                    </div>
                </div>
            </div>
            <button class="btn-next">Next</button>
        </section>
        <section class="default light">
            <div class="section-title">Novas Inserções</div>
            <div class="section-desc"></div>
            <div class="section-body">
                <div class="section-aboutus">
                    <div class="section-aboutus--left">
                        <h4>Ambiente</h4>
                        <a class="button" style="display: inline-block; margin-bottom:5px;" 
                            href="{% url 'ambientes:save_ambiente' %}">Cadastrar um Ambiente</a>                         
                    </div>
                    <div class="section-aboutus--rigth">
                        <h4>Aparelho</h4>
                        <a class="button" style="display: inline-block; margin-bottom:5px;" 
                            href="{% url 'aparelhos:save_aparelho' %}">Cadastrar um Aparelho</a>
                            <a class="button" style="display: inline-block; margin-bottom:5px;" 
                            href="{% url 'aparelhos:relation' %}">Relacionamte</a>                         
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}